-- ============================================================
-- Migration: 20260704_create_topvisor_project_scope
-- Description: Canonical active business scope table.
--
-- This table is the canonical active business scope for TopVisor
-- portfolio reports. It replaces raw TopVisor metadata expansion
-- (which produced 418 incorrect project-region pairs) with a
-- curated, row_key-driven scope.
--
-- Matching to daily data (data_daily) must be strict by row_key,
-- not by project_id or region_index alone.
-- ============================================================

create table public.topvisor_project_scope (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  project_name text,
  site text,
  region_index integer not null,
  region_key text,
  region_name text,
  searcher_key integer not null,
  search_engine text not null,
  row_key text not null,
  is_active boolean not null default true,
  scope_source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint topvisor_project_scope_row_key_uq
    unique (row_key),
  constraint topvisor_project_scope_project_region_searcher_uq
    unique (project_id, region_index, searcher_key),
  constraint topvisor_project_scope_search_engine_check
    check (search_engine in ('Yandex', 'Google')),
  constraint topvisor_project_scope_row_key_not_empty
    check (btrim(row_key) <> ''),
  constraint topvisor_project_scope_scope_source_not_empty
    check (btrim(scope_source) <> '')
);

-- indexes for common query patterns
create index if not exists topvisor_project_scope_is_active_idx
  on public.topvisor_project_scope (is_active);

create index if not exists topvisor_project_scope_project_id_idx
  on public.topvisor_project_scope (project_id);

create index if not exists topvisor_project_scope_search_engine_idx
  on public.topvisor_project_scope (search_engine);

create index if not exists topvisor_project_scope_region_index_idx
  on public.topvisor_project_scope (region_index);

-- partial index: only active rows (used for active scope queries)
create index if not exists topvisor_project_scope_active_row_key_idx
  on public.topvisor_project_scope (row_key)
  where is_active = true;

-- row level security
alter table public.topvisor_project_scope enable row level security;